export const historicalAccounts = [
  { id: "first-planets", title: "1992: Timing reveals the first confirmed planets", details: <>Aleksander Wolszczan and Dale Frail found planets around pulsar PSR B1257+12 by measuring changes in the arrival times of its radio pulses. Pulsar timing proved planets existed beyond the Solar System, but it applies to an unusual kind of stellar remnant. <a className="text-teal-700 underline" href="https://science.nasa.gov/universe/exoplanets/will-the-real-first-exoplanet-please-stand-up/" target="_blank" rel="noreferrer">NASA history</a></> },
  { id: "sun-like-star", title: "1995: A planet around a Sun-like star", details: <>Michel Mayor and Didier Queloz detected 51 Pegasi b through radial velocity: its gravity makes its star move slightly toward and away from Earth. Improved spectrographs made such small shifts measurable, and radial velocity became an important early discovery method. <a className="text-teal-700 underline" href="https://science.nasa.gov/universe/exoplanets/will-the-real-first-exoplanet-please-stand-up/" target="_blank" rel="noreferrer">NASA history</a></> },
  { id: "new-signals", title: "1999-2005: New signals and new kinds of planets", details: <>Teams including David Charbonneau and Greg Henry observed HD 209458 b crossing its star in 1999, establishing transits as a way to measure a planet&apos;s size. The OGLE and MOA collaborations then found a planet through gravitational microlensing, and Gael Chauvin&apos;s team imaged 2M1207 b, confirmed in 2005. These methods reached planets that stellar wobble alone could not describe. <a className="text-teal-700 underline" href="https://science.nasa.gov/missions/hubble/astronomers-ponder-lack-of-planets-in-globular-cluster/" target="_blank" rel="noreferrer">Transits</a> · <a className="text-teal-700 underline" href="https://science.nasa.gov/missions/hubble/hubble-identifies-stellar-companion-to-distant-planet/" target="_blank" rel="noreferrer">Microlensing</a> · <a className="text-teal-700 underline" href="https://www.hq.eso.org/public/news/eso0515/" target="_blank" rel="noreferrer">Imaging</a></> },
  { id: "kepler", title: "2009-2016: Kepler scales up transit searches", details: <>Kepler, led by principal investigator William Borucki, monitored many stars continuously. Better analysis and statistical validation turned candidate signals into large batches of confirmed planets: NASA announced 715 in 2014 and 1,284 in 2016. The spikes in those years partly reflect when planets were validated and reported, not a sudden change in how many planets exist. <a className="text-teal-700 underline" href="https://www.nasa.gov/news-release/nasas-kepler-mission-announces-a-planet-bonanza-715-new-worlds/" target="_blank" rel="noreferrer">2014 announcement</a> · <a className="text-teal-700 underline" href="https://www.nasa.gov/news-release/nasas-kepler-mission-announces-largest-collection-of-planets-ever-discovered/" target="_blank" rel="noreferrer">2016 announcement</a></> },
  { id: "tess", title: "2018-present: Bright nearby stars and follow-up", details: <>TESS, launched in 2018 under principal investigator George Ricker, surveys much of the sky for transits around relatively bright, nearby stars. Ground-based radial-velocity observations help confirm candidates and measure masses; telescopes such as Webb can then study some atmospheres. Candidate counts should not be confused with confirmed discoveries. <a className="text-teal-700 underline" href="https://science.nasa.gov/mission/tess/" target="_blank" rel="noreferrer">TESS mission</a> · <a className="text-teal-700 underline" href="https://science.nasa.gov/universe/exoplanets/follow-that-planet-how-astronomers-chase-new-worlds-in-tess-data/" target="_blank" rel="noreferrer">Follow-up</a></> },
  { id: "next-missions", title: "What comes next", details: <>Astrometry measures a star&apos;s tiny motion across the sky, while microlensing can reveal planets at wider separations from their stars. Gaia&apos;s future releases are expected to expand astrometric candidates, and the recently launched Roman Space Telescope is preparing for a microlensing survey. Neither future yield is included in this snapshot. <a className="text-teal-700 underline" href="https://www.cosmos.esa.int/web/gaia/iow_20240422" target="_blank" rel="noreferrer">Gaia</a> · <a className="text-teal-700 underline" href="https://science.nasa.gov/mission/roman-space-telescope/" target="_blank" rel="noreferrer">Roman</a></> },
];

export const discoveryMilestones = [
  { year: 1992, label: "First confirmed planets", title: "Timing reveals the first confirmed planets", historyId: "first-planets", summary: "Changes in a pulsar’s radio-pulse timing revealed two planets around PSR B1257+12. These first confirmed worlds orbit a stellar remnant, rather than a Sun-like star." },
  { year: 1995, label: "51 Pegasi b", title: "A planet around a Sun-like star", historyId: "sun-like-star", summary: "Mayor and Queloz identified 51 Pegasi b through its star’s radial-velocity signal. Precise spectrographs opened a new way to find planets around ordinary stars." },
  { year: 1999, label: "A planet crosses its star", title: "A known planet reveals a transit", historyId: "new-signals", summary: "HD 209458 b, already found by radial velocity, was observed crossing its star. The transit helped measure its size. The catalog counts a planet under its discovery method, even when another method later studies it." },
  { year: 2014, label: "Kepler’s first surge", title: "Kepler validates planets in large batches", historyId: "kepler", summary: "NASA announced 715 newly verified Kepler planets using statistical validation. This helps explain the surge in discoveries; the year’s catalog total also includes other discoveries and is not the announcement’s batch size." },
  { year: 2016, label: "Kepler’s largest surge", title: "Kepler adds another large validated sample", historyId: "kepler", summary: "NASA announced 1,284 newly validated Kepler planets. Large batches reflect when evidence was validated and reported, rather than a sudden increase in how many planets exist. The year’s catalog total includes more than this announcement." },
  { year: 2018, label: "TESS launches", title: "The search turns to bright nearby stars", historyId: "tess", summary: "TESS launched in 2018 to survey much of the sky for transits around relatively bright, nearby stars. Follow-up observations help confirm candidates and measure masses. The chart includes discoveries from all surveys, not just TESS." },
];
